// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client/src/main/protos/basemessage.proto

package com.creditsesame.microservice.personalloan.protobuf;

public final class BaseMessageProtos {
  private BaseMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.BaseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 txtid = 1;</code>
     */
    boolean hasTxtid();
    /**
     * <code>required int32 txtid = 1;</code>
     */
    int getTxtid();
  }
  /**
   * Protobuf type {@code protobuf.BaseMessage}
   *
   * <pre>
   **
   *BaseMessage is just supposed to be included in every other message, this is just to ensure that every
   *message includes certain required or optional pieces for auditing or security purposes
   *This is still incomplete and it is only intented to show the capacity of protobuf of composition, check
   *personallender.proto to see how this file is used
   * </pre>
   */
  public static final class BaseMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.BaseMessage)
      BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseMessage defaultInstance;
    public static BaseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              txtid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.internal_static_protobuf_BaseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.internal_static_protobuf_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.class, com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TXTID_FIELD_NUMBER = 1;
    private int txtid_;
    /**
     * <code>required int32 txtid = 1;</code>
     */
    public boolean hasTxtid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 txtid = 1;</code>
     */
    public int getTxtid() {
      return txtid_;
    }

    private void initFields() {
      txtid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTxtid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, txtid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, txtid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.BaseMessage}
     *
     * <pre>
     **
     *BaseMessage is just supposed to be included in every other message, this is just to ensure that every
     *message includes certain required or optional pieces for auditing or security purposes
     *This is still incomplete and it is only intented to show the capacity of protobuf of composition, check
     *personallender.proto to see how this file is used
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.BaseMessage)
        com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.internal_static_protobuf_BaseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.internal_static_protobuf_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.class, com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.Builder.class);
      }

      // Construct using com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        txtid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.internal_static_protobuf_BaseMessage_descriptor;
      }

      public com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage getDefaultInstanceForType() {
        return com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.getDefaultInstance();
      }

      public com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage build() {
        com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage buildPartial() {
        com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage result = new com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.txtid_ = txtid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage) {
          return mergeFrom((com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage other) {
        if (other == com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.getDefaultInstance()) return this;
        if (other.hasTxtid()) {
          setTxtid(other.getTxtid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTxtid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int txtid_ ;
      /**
       * <code>required int32 txtid = 1;</code>
       */
      public boolean hasTxtid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 txtid = 1;</code>
       */
      public int getTxtid() {
        return txtid_;
      }
      /**
       * <code>required int32 txtid = 1;</code>
       */
      public Builder setTxtid(int value) {
        bitField0_ |= 0x00000001;
        txtid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 txtid = 1;</code>
       */
      public Builder clearTxtid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        txtid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.BaseMessage)
    }

    static {
      defaultInstance = new BaseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.BaseMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_BaseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_BaseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(Client/src/main/protos/basemessage.pro" +
      "to\022\010protobuf\"\034\n\013BaseMessage\022\r\n\005txtid\030\001 \002" +
      "(\005BH\n3com.creditsesame.microservice.pers" +
      "onalloan.protobufB\021BaseMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_BaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_BaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_BaseMessage_descriptor,
        new java.lang.String[] { "Txtid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
