// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client/src/main/protos/personallender.proto

package com.creditsesame.microservice.personalloan.protobuf;

public final class PersonalLenderProtos {
  private PersonalLenderProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonalLenderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.PersonalLender)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protobuf.BaseMessage basemessage = 1;</code>
     */
    boolean hasBasemessage();
    /**
     * <code>required .protobuf.BaseMessage basemessage = 1;</code>
     */
    com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage getBasemessage();
    /**
     * <code>required .protobuf.BaseMessage basemessage = 1;</code>
     */
    com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessageOrBuilder getBasemessageOrBuilder();

    /**
     * <code>optional int64 id = 2;</code>
     *
     * <pre>
     *required string id = 1;
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 2;</code>
     *
     * <pre>
     *required string id = 1;
     * </pre>
     */
    long getId();

    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string link = 4;</code>
     */
    boolean hasLink();
    /**
     * <code>optional string link = 4;</code>
     */
    java.lang.String getLink();
    /**
     * <code>optional string link = 4;</code>
     */
    com.google.protobuf.ByteString
        getLinkBytes();

    /**
     * <code>optional string imageLogoUrl = 5;</code>
     */
    boolean hasImageLogoUrl();
    /**
     * <code>optional string imageLogoUrl = 5;</code>
     */
    java.lang.String getImageLogoUrl();
    /**
     * <code>optional string imageLogoUrl = 5;</code>
     */
    com.google.protobuf.ByteString
        getImageLogoUrlBytes();

    /**
     * <code>optional string bullets = 6;</code>
     */
    boolean hasBullets();
    /**
     * <code>optional string bullets = 6;</code>
     */
    java.lang.String getBullets();
    /**
     * <code>optional string bullets = 6;</code>
     */
    com.google.protobuf.ByteString
        getBulletsBytes();

    /**
     * <code>optional string rightSideText = 7;</code>
     */
    boolean hasRightSideText();
    /**
     * <code>optional string rightSideText = 7;</code>
     */
    java.lang.String getRightSideText();
    /**
     * <code>optional string rightSideText = 7;</code>
     */
    com.google.protobuf.ByteString
        getRightSideTextBytes();

    /**
     * <code>optional string aboutText = 8;</code>
     */
    boolean hasAboutText();
    /**
     * <code>optional string aboutText = 8;</code>
     */
    java.lang.String getAboutText();
    /**
     * <code>optional string aboutText = 8;</code>
     */
    com.google.protobuf.ByteString
        getAboutTextBytes();
  }
  /**
   * Protobuf type {@code protobuf.PersonalLender}
   *
   * <pre>
   *Just an example of .proto file that contains a PersonalLender object. it includes BaseMessage, check
   *the general gradle build file to see how these proto files are compiled to make it usable by the application
   *service and client
   * </pre>
   */
  public static final class PersonalLender extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.PersonalLender)
      PersonalLenderOrBuilder {
    // Use PersonalLender.newBuilder() to construct.
    private PersonalLender(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PersonalLender(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PersonalLender defaultInstance;
    public static PersonalLender getDefaultInstance() {
      return defaultInstance;
    }

    public PersonalLender getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PersonalLender(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = basemessage_.toBuilder();
              }
              basemessage_ = input.readMessage(com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(basemessage_);
                basemessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              link_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              imageLogoUrl_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              bullets_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              rightSideText_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              aboutText_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.internal_static_protobuf_PersonalLender_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.internal_static_protobuf_PersonalLender_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender.class, com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender.Builder.class);
    }

    public static com.google.protobuf.Parser<PersonalLender> PARSER =
        new com.google.protobuf.AbstractParser<PersonalLender>() {
      public PersonalLender parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonalLender(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersonalLender> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BASEMESSAGE_FIELD_NUMBER = 1;
    private com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage basemessage_;
    /**
     * <code>required .protobuf.BaseMessage basemessage = 1;</code>
     */
    public boolean hasBasemessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protobuf.BaseMessage basemessage = 1;</code>
     */
    public com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage getBasemessage() {
      return basemessage_;
    }
    /**
     * <code>required .protobuf.BaseMessage basemessage = 1;</code>
     */
    public com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessageOrBuilder getBasemessageOrBuilder() {
      return basemessage_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>optional int64 id = 2;</code>
     *
     * <pre>
     *required string id = 1;
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 id = 2;</code>
     *
     * <pre>
     *required string id = 1;
     * </pre>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINK_FIELD_NUMBER = 4;
    private java.lang.Object link_;
    /**
     * <code>optional string link = 4;</code>
     */
    public boolean hasLink() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string link = 4;</code>
     */
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          link_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string link = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGELOGOURL_FIELD_NUMBER = 5;
    private java.lang.Object imageLogoUrl_;
    /**
     * <code>optional string imageLogoUrl = 5;</code>
     */
    public boolean hasImageLogoUrl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string imageLogoUrl = 5;</code>
     */
    public java.lang.String getImageLogoUrl() {
      java.lang.Object ref = imageLogoUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imageLogoUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imageLogoUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getImageLogoUrlBytes() {
      java.lang.Object ref = imageLogoUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageLogoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BULLETS_FIELD_NUMBER = 6;
    private java.lang.Object bullets_;
    /**
     * <code>optional string bullets = 6;</code>
     */
    public boolean hasBullets() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string bullets = 6;</code>
     */
    public java.lang.String getBullets() {
      java.lang.Object ref = bullets_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bullets_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bullets = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBulletsBytes() {
      java.lang.Object ref = bullets_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bullets_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RIGHTSIDETEXT_FIELD_NUMBER = 7;
    private java.lang.Object rightSideText_;
    /**
     * <code>optional string rightSideText = 7;</code>
     */
    public boolean hasRightSideText() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string rightSideText = 7;</code>
     */
    public java.lang.String getRightSideText() {
      java.lang.Object ref = rightSideText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rightSideText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rightSideText = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRightSideTextBytes() {
      java.lang.Object ref = rightSideText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rightSideText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ABOUTTEXT_FIELD_NUMBER = 8;
    private java.lang.Object aboutText_;
    /**
     * <code>optional string aboutText = 8;</code>
     */
    public boolean hasAboutText() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string aboutText = 8;</code>
     */
    public java.lang.String getAboutText() {
      java.lang.Object ref = aboutText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          aboutText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string aboutText = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAboutTextBytes() {
      java.lang.Object ref = aboutText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aboutText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      basemessage_ = com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.getDefaultInstance();
      id_ = 0L;
      name_ = "";
      link_ = "";
      imageLogoUrl_ = "";
      bullets_ = "";
      rightSideText_ = "";
      aboutText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBasemessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBasemessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, basemessage_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLinkBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getImageLogoUrlBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getBulletsBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getRightSideTextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getAboutTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, basemessage_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLinkBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getImageLogoUrlBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getBulletsBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getRightSideTextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getAboutTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.PersonalLender}
     *
     * <pre>
     *Just an example of .proto file that contains a PersonalLender object. it includes BaseMessage, check
     *the general gradle build file to see how these proto files are compiled to make it usable by the application
     *service and client
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.PersonalLender)
        com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLenderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.internal_static_protobuf_PersonalLender_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.internal_static_protobuf_PersonalLender_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender.class, com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender.Builder.class);
      }

      // Construct using com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBasemessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (basemessageBuilder_ == null) {
          basemessage_ = com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.getDefaultInstance();
        } else {
          basemessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        imageLogoUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        bullets_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        rightSideText_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        aboutText_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.internal_static_protobuf_PersonalLender_descriptor;
      }

      public com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender getDefaultInstanceForType() {
        return com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender.getDefaultInstance();
      }

      public com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender build() {
        com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender buildPartial() {
        com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender result = new com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (basemessageBuilder_ == null) {
          result.basemessage_ = basemessage_;
        } else {
          result.basemessage_ = basemessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.imageLogoUrl_ = imageLogoUrl_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bullets_ = bullets_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.rightSideText_ = rightSideText_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.aboutText_ = aboutText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender) {
          return mergeFrom((com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender other) {
        if (other == com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender.getDefaultInstance()) return this;
        if (other.hasBasemessage()) {
          mergeBasemessage(other.getBasemessage());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLink()) {
          bitField0_ |= 0x00000008;
          link_ = other.link_;
          onChanged();
        }
        if (other.hasImageLogoUrl()) {
          bitField0_ |= 0x00000010;
          imageLogoUrl_ = other.imageLogoUrl_;
          onChanged();
        }
        if (other.hasBullets()) {
          bitField0_ |= 0x00000020;
          bullets_ = other.bullets_;
          onChanged();
        }
        if (other.hasRightSideText()) {
          bitField0_ |= 0x00000040;
          rightSideText_ = other.rightSideText_;
          onChanged();
        }
        if (other.hasAboutText()) {
          bitField0_ |= 0x00000080;
          aboutText_ = other.aboutText_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBasemessage()) {
          
          return false;
        }
        if (!getBasemessage().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.creditsesame.microservice.personalloan.protobuf.PersonalLenderProtos.PersonalLender) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage basemessage_ = com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage, com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.Builder, com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessageOrBuilder> basemessageBuilder_;
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      public boolean hasBasemessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      public com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage getBasemessage() {
        if (basemessageBuilder_ == null) {
          return basemessage_;
        } else {
          return basemessageBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      public Builder setBasemessage(com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage value) {
        if (basemessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          basemessage_ = value;
          onChanged();
        } else {
          basemessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      public Builder setBasemessage(
          com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.Builder builderForValue) {
        if (basemessageBuilder_ == null) {
          basemessage_ = builderForValue.build();
          onChanged();
        } else {
          basemessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      public Builder mergeBasemessage(com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage value) {
        if (basemessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              basemessage_ != com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.getDefaultInstance()) {
            basemessage_ =
              com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.newBuilder(basemessage_).mergeFrom(value).buildPartial();
          } else {
            basemessage_ = value;
          }
          onChanged();
        } else {
          basemessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      public Builder clearBasemessage() {
        if (basemessageBuilder_ == null) {
          basemessage_ = com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.getDefaultInstance();
          onChanged();
        } else {
          basemessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      public com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.Builder getBasemessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBasemessageFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      public com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessageOrBuilder getBasemessageOrBuilder() {
        if (basemessageBuilder_ != null) {
          return basemessageBuilder_.getMessageOrBuilder();
        } else {
          return basemessage_;
        }
      }
      /**
       * <code>required .protobuf.BaseMessage basemessage = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage, com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.Builder, com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessageOrBuilder> 
          getBasemessageFieldBuilder() {
        if (basemessageBuilder_ == null) {
          basemessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage, com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessage.Builder, com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.BaseMessageOrBuilder>(
                  getBasemessage(),
                  getParentForChildren(),
                  isClean());
          basemessage_ = null;
        }
        return basemessageBuilder_;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 2;</code>
       *
       * <pre>
       *required string id = 1;
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 id = 2;</code>
       *
       * <pre>
       *required string id = 1;
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 2;</code>
       *
       * <pre>
       *required string id = 1;
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 2;</code>
       *
       * <pre>
       *required string id = 1;
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object link_ = "";
      /**
       * <code>optional string link = 4;</code>
       */
      public boolean hasLink() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string link = 4;</code>
       */
      public java.lang.String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            link_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string link = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLinkBytes() {
        java.lang.Object ref = link_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          link_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string link = 4;</code>
       */
      public Builder setLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        link_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string link = 4;</code>
       */
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000008);
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      /**
       * <code>optional string link = 4;</code>
       */
      public Builder setLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        link_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageLogoUrl_ = "";
      /**
       * <code>optional string imageLogoUrl = 5;</code>
       */
      public boolean hasImageLogoUrl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string imageLogoUrl = 5;</code>
       */
      public java.lang.String getImageLogoUrl() {
        java.lang.Object ref = imageLogoUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            imageLogoUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imageLogoUrl = 5;</code>
       */
      public com.google.protobuf.ByteString
          getImageLogoUrlBytes() {
        java.lang.Object ref = imageLogoUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageLogoUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imageLogoUrl = 5;</code>
       */
      public Builder setImageLogoUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        imageLogoUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageLogoUrl = 5;</code>
       */
      public Builder clearImageLogoUrl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        imageLogoUrl_ = getDefaultInstance().getImageLogoUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imageLogoUrl = 5;</code>
       */
      public Builder setImageLogoUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        imageLogoUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bullets_ = "";
      /**
       * <code>optional string bullets = 6;</code>
       */
      public boolean hasBullets() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string bullets = 6;</code>
       */
      public java.lang.String getBullets() {
        java.lang.Object ref = bullets_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bullets_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bullets = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBulletsBytes() {
        java.lang.Object ref = bullets_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bullets_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bullets = 6;</code>
       */
      public Builder setBullets(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bullets_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bullets = 6;</code>
       */
      public Builder clearBullets() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bullets_ = getDefaultInstance().getBullets();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bullets = 6;</code>
       */
      public Builder setBulletsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bullets_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rightSideText_ = "";
      /**
       * <code>optional string rightSideText = 7;</code>
       */
      public boolean hasRightSideText() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string rightSideText = 7;</code>
       */
      public java.lang.String getRightSideText() {
        java.lang.Object ref = rightSideText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            rightSideText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rightSideText = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRightSideTextBytes() {
        java.lang.Object ref = rightSideText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rightSideText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rightSideText = 7;</code>
       */
      public Builder setRightSideText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        rightSideText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rightSideText = 7;</code>
       */
      public Builder clearRightSideText() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rightSideText_ = getDefaultInstance().getRightSideText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rightSideText = 7;</code>
       */
      public Builder setRightSideTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        rightSideText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object aboutText_ = "";
      /**
       * <code>optional string aboutText = 8;</code>
       */
      public boolean hasAboutText() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string aboutText = 8;</code>
       */
      public java.lang.String getAboutText() {
        java.lang.Object ref = aboutText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            aboutText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string aboutText = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAboutTextBytes() {
        java.lang.Object ref = aboutText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aboutText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string aboutText = 8;</code>
       */
      public Builder setAboutText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        aboutText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string aboutText = 8;</code>
       */
      public Builder clearAboutText() {
        bitField0_ = (bitField0_ & ~0x00000080);
        aboutText_ = getDefaultInstance().getAboutText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string aboutText = 8;</code>
       */
      public Builder setAboutTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        aboutText_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.PersonalLender)
    }

    static {
      defaultInstance = new PersonalLender(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.PersonalLender)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_PersonalLender_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_PersonalLender_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+Client/src/main/protos/personallender." +
      "proto\022\010protobuf\032(Client/src/main/protos/" +
      "basemessage.proto\"\265\001\n\016PersonalLender\022*\n\013" +
      "basemessage\030\001 \002(\0132\025.protobuf.BaseMessage" +
      "\022\n\n\002id\030\002 \001(\003\022\014\n\004name\030\003 \001(\t\022\014\n\004link\030\004 \001(\t" +
      "\022\024\n\014imageLogoUrl\030\005 \001(\t\022\017\n\007bullets\030\006 \001(\t\022" +
      "\025\n\rrightSideText\030\007 \001(\t\022\021\n\taboutText\030\010 \001(" +
      "\tBK\n3com.creditsesame.microservice.perso" +
      "nalloan.protobufB\024PersonalLenderProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.getDescriptor(),
        }, assigner);
    internal_static_protobuf_PersonalLender_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_PersonalLender_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_PersonalLender_descriptor,
        new java.lang.String[] { "Basemessage", "Id", "Name", "Link", "ImageLogoUrl", "Bullets", "RightSideText", "AboutText", });
    com.creditsesame.microservice.personalloan.protobuf.BaseMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
